// Auto-generated by f2c (figma-to-code)
// https://github.com/f2c-cli

<template>
  <button
    class="inline-flex flex-col items-center justify-center rounded-full cursor-pointer border-none"
    :style="{
      backgroundColor: 'rgb(13, 13, 13)',
      padding: '0 16px',
      gap: '8px',
      minHeight: '32px',
    }"
    @click="handleClick"
  >
    <div
      class="flex flex-row items-center justify-center"
      :style="{
        gap: '8px',
        height: '32px',
      }"
    >
      <span
        class="text-white text-sm font-normal leading-[22px] whitespace-nowrap"
      >
        {{ label }}
      </span>
    </div>
  </button>
</template>

<script setup lang="ts">
interface Props {
  label?: string
}

const props = withDefaults(defineProps<Props>(), {
  label: '确定',
})

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

function handleClick(event: MouseEvent) {
  emit('click', event)
}
</script>

<style scoped>
button:hover {
  opacity: 0.85;
}

button:active {
  opacity: 0.7;
}
</style>